### ISSUE TITLE
Mongoose 4.0 does not work with Mongo 3.0 wiredTiger engine?

### ISSUE THREAD

**Issue by mattma** [LearnBoost/mongoose#2704]
Here is my setup. 

```bash
 ➜ mongod --version                                                        2 ↵
db version v3.0.0-rc6
git version: 8dd41ae58040dfa09c633c05ce5752d46402f9c5

Mongoose version
4.0.0-rc1
```

I have an existing application which could smoothly run on Mongoose@4.0.0-rc1 and  mongod@2.6.7.

After I watched the new Mongodb@3.0 release webniar, I started to play with new shining **3.0.0-rc6**. 

I first use `mongodump@3.0.0-rc6` to dump my database into a folder, then use `mongorestore@3.0.0-rc6` to restore the database back with the database name. I changed my `storageEngine` from `MMVP` to `wiredTiger` by running `mongod --storageEngine=wiredTiger`. I works since I removed my old `--dbpath /data/db` I am able to use `CRUD` on my `mongo` CLI to query the database. All the collections, documents are still there. 

Here is the problem, when I am querying using `mongo` command in terminal, it works fine. Actually, trying to use my application to query anything via `mongoose@4.0.0-rc1` and it did not work. 

In `mongoose` `package.json`, there is a line `"mongodb": "2.0.14",`, is this causing the problem? Should I manually update the `mongodb` dependencies?

**Comment by vkarpov15** [comment]
What exactly doesn't work? Can you provide me a script that I can run that reproduces this?

**Comment by mattma** [comment]
@vkarpov15 You are right. It works out of the box. I was in the middle of refactoring while I play with new Mongo 3.0.

Anyway, I knew that you works at MongoDB inc and are a maintainer of Mongoose project and node-mongodb-native. 

Is mongoose always going to sync with the latest greatest feature of Mongodb 3.0 and onwards? I recently noticed that `mongoskin` is not being maintained and looking for maintainers. I am afraid if I bet too much on Mongoose, then it happens to be like `mongoskin` project. 

I am sure that `node-mongodb-native` is officially Node.js driver repo by MongoDB inc. But I love the mongoose schema concept.

**Comment by vkarpov15** [comment]
So mongoose 4 right now relies on node-mongodb-native 2.0.16 if I recall correctly, so it should work fine with mongodb 3.0.

Mongoose will continue to be supported for the foreseeable future and will support MongoDB 3.0. As for mongoskin, do you know who's maintaining that? I can take over that project as well - I know mongoskin is pretty popular.

**Comment by mattma** [comment]
[mongoskin](https://www.npmjs.com/package/mongoskin)

Current maintained by 

guileen@gmail.com
@guileen on npm

fengmk2@gmail.com
@fengmk2 on npm

If I am right, they are both chinese (same like myself), @fengmk2 works at Alibaba. If needed, I could ask `fengmk2` for you since I knew his co-work `dead-horse`

**Comment by mattma** [comment]
By the way, when I start my node server which connect to `mongodb@3.0` database. 

I got this error here. 

```bash
child_process: customFds option is deprecated, use stdio instead.
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

First error is Node error, I need some research to fix that. The second error is related to the latest "wiredTiger". Any idea how to fix?

**Comment by fengmk2** [comment]
We have stop using mongodb for a long time.
@vkarpov15 if you have time to maintain mongoskin, I can add you both to the team. And also give you the npm publish access.

**Comment by mattma** [comment]
@fengmk2 新年好！恭喜发财！

@vkarpov15 works for MongoDB inc and he is the maintainer of the official Node.js Mongodb driver [node-mongodb-native](https://github.com/mongodb/node-mongodb-native) and [mongoose](https://github.com/learnboost/mongoose). 

He actively answers MongoDB questions on Mongoose Gitter, Node-Mongodb-native Gitter, StackOverflow Mongo channel, and more. He is highly educated individual who knows MongoDB in and out, and backed by MongoDB inc. Hopefully, it could work out for both parties. 

@fengmk2 You have done some amazing work for Node.js community. Thank you for that. I recently noticed that you are driving the initiative to push `io.js` movement in China. `CNPM` is another awesome project that you have been working on. I am nowhere close to what you have been. It would be super cool that we could connect. Maybe meet you in person in the future at HangZhou.

**Comment by fengmk2** [comment]
@mattma Keep in touch, I have follow you on twitter. It's pleasure to show you what we're doing.

**Comment by vkarpov15** [comment]
2nd is an issue that tends to pop up on Windows, haven't quite had a chance to look into it. See #2705, etc.

And @fengmk2 absolutely, add me on. I do remember running into mongoskin a few times and being a bit disappointed that it lagged behind the node driver. I'm vkarpov15 on npm as well as github.

**Comment by mattma** [comment]
Thanks @vkarpov15. I will dive in deeper on that. Thanks for what you have done for Mongo community. Let us keep in touch!

**Comment by fengmk2** [comment]
@vkarpov15 already sent you the invitation. I will add you to the npm authors too.

**Comment by LeoDutra** [comment]
@fengmk2 what are you using in place of MongoDB? Best regards.

**Comment by fengmk2** [comment]
@LeoDutra MySQL :)

**Comment by LeoDutra** [comment]
:)​

**Comment by wayofthefuture** [comment]
Does anyone know how to make Mongoose create a WiredTiger collection when I create the model or first write to the database using the model (assuming it does not exist yet)?

**Comment by vkarpov15** [comment]
That's up to mongodb, not mongoose. You need to configure your mongodb server to use WT, mongoose has no idea what storage engine the underlying mongodb server uses

**Comment by wayofthefuture** [comment]
Thanks... I think I found it here: https://docs.mongodb.com/v3.2/tutorial/change-standalone-wiredtiger/
